name: Update tap

on: 
  repository_dispatch:
    types: [my-release]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Update recipe
        shell: bash
        run: ./update.sh "${{ github.event.client_payload.tag }}"

      - uses: stefanzweifel/git-auto-commit-action@v4.0.0
        with:
            commit_message: Update recipe to version "${{ github.event.client_payload.tag }}"

            # Optional glob pattern of files which should be added to the commit
            file_pattern: gotop.rb

            # Optional commit user and author settings
            commit_user_name: Tap Updater
            commit_user_email: ser@ser1.net
            commit_author: Tap Updater <ser@ser1.net>
